### ISSUE TITLE
Is the computation of compequ correct? 

### ISSUE THREAD

**Issue by voigtstefan** [ckscheuch/rAnomalies#10]
Your code looks as follows

         compequ = log(me / me_l1) - (log(prcc_f) - log(prcc_f_l5)), # composite equity issuance

However, according to the paper shouldn't it be 

         compequ = log(me / me_l5) - (log(prcc_f) - log(prcc_f_l5)), # composite equity issuance

If so, the associated `left_joins` have to be changed as well.

**Comment by ckscheuch** [comment]
thanks
