### ISSUE TITLE
Is there a bug in Sigma?

### ISSUE THREAD

**Issue by voigtstefan** [ckscheuch/rAnomalies#11]
In your code you write:

    crsp.daily.sum <- crsp.daily.sum %>%
          mutate(sigma = sqrt(252 / trading_days_l1 + trading_days_l2 + trading_days_l3 - 1) * 
                        (sum_ret_sqr_l1 + sum_ret_sqr_l2 + sum_ret_sqr_l3) ....

Shouldn't it be (brackets around the trading days)?

    crsp.daily.sum <- crsp.daily.sum %>%
          mutate(sigma = sqrt(252 / (trading_days_l1 + trading_days_l2 + trading_days_l3) - 1) * 
                        (sum_ret_sqr_l1 + sum_ret_sqr_l2 + sum_ret_sqr_l3) ....

**Comment by ckscheuch** [comment]
Fixed
